spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaoyuanpe?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 17854258952
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis:
#  # 若资源映射xml文件在resources目录
#  mapper-locations: classpath:/mapper/*./xml
#  # 定义包别名使用pojo时可以直接使用pojo下的类型名称而不用加包名
#  type-aliases-package:
