spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaoyuanpe?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 17854258952
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    check-template-location: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

#mybatis:
#  # 若资源映射xml文件在resources目录
#  mapper-locations: classpath:/mapper/*./xml
#  # 定义包别名使用pojo时可以直接使用pojo下的类型名称而不用加包名
#  type-aliases-package:
logging:
  config: classpath:logback-spring.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql